#### Node Parameters ####
# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"


#### Core API Parameters ####
# Port which you wish the Oracle Core GET API server to run on.
# Note, the Oracle Core POST API server (to submit datapoints) will be on
# `core_api_port` + 1.
core_api_port: "9090"


#### Local Oracle Parameters ####
# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"
# The base fee constant that all action txs use to calculate fee.
# Adjust if blockchain is congested/higher tx fees are required.
base_fee: 1000000


#### Pool Token Ids ####
# ID of the oracle pool NFT
oracle_pool_nft: "08b59b14e4fdd60e5952314adbaa8b4e00bc0f0b676872a5224d3bf8591074cd"
# ID of the oracle pool participant token
oracle_pool_participant_token: "0f8c7c7f4a203c69fddf147a16599d78341609bd9f129dc540bd225f90f86d60"


#### Pool Smart Contract Addresses ####
# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "USNVj4rN2DctyA1X4WboqbahX4giqUDB9uQZWoGw686pmd2xjmGFQatVMQSqFV9kk7c9D21wr4kfLQkj2U4EyEt9YD2GTdwevU9QqBzmAaY45YD2mgSdforG3GnNJzcyMPJfn5VcKqhnQcWTehgXEaSzHHyFT2AoXv4ZygsaH52iBTkyaqRwJX4JvZ14Zm4Lj9mFodj3usYHv8MMCESKNbKifzex3kfSuhYC5Hu9kBgQGEsssfF4nLtVxzKXU7B5LmzQ5EyCJS6frkdBDppYn2aXAgEiNDGEu7zMuDQbh9iEJhbAYtQStYqTPjxyhhnGS4kB1GFScWj2K73c2gPkEdfbu2cbx5Zr8ntzGUzykq2h2EUwCRyQMN3gXNesy9vPQXYEaHLbdtnGgYYYNf3tTkHLqfvJFmpfXUJrFsxnsjByVok8HSsoM4HQkXX3gQGxjTJvd96A7Qt5gU42yPzNYTSEgQZP2Kdh36kxKykG"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "Gxd4hMRT6Lbs5atqVxppyRNa4pKntcdMiAzAnmobNoncQKGBzo7pXBnx2u2D9R9nSfFvtoePzrjxZReT3mx5S4Mg1yjZysXrZHXT2Fb8DJ171ipa5FUbN6skZduVHnjgcpHKymxp9PBMb7j7bXirPRdVdx27qBzUcHyyaHunXRDC7qXRHxESSY3rdzLAX61XLci3SF1PdgBYhSwDgwtuDCDtKBFVvEWXg5eWdJ7xEv8rYYK6Nrrhu8mnRUoiMN1PGxo1e4fzz44qHnVFYnLFp64TNLH6nffmYxEWBWkjLBvkhYR3xBpA8FaF7TosmjsoMu3nEzpNUMrL8iQgFhp6FmHxUWswajtpyNwrCQDKa4oKqWyk88SjxVXX94Eussf9BJvuneiKXx2rgZ"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "jL2aaqw6XU61SZznviQU8yUY3fZwZR1fYeeVm1s1Lqhe4Gbm5PARBrCGtK4ZV5PWcmiGEhSxVMMPrsrefW2SPifmVQ6jCdJvhFebWTWEa9mbyKH6NAsVedFx7n6MoCoxH4uYaBacLRbH8PYiwLgMC6V4C8QkHRURvDLSBfMhVuEWsp4AQmCJAVDm8mUxCBJAvT4U4vzwrJvfjdizNTHV1scyFvMajLFXwvgEtLd4AYq4wi7oDPik7dERUqXf8"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "zLSQDVBaEyMzPngLk2R8agtkBKqRQMhGxrQqvUzAtxrH9Jbn79STTtiiQ4g6oCzFBvKjxAPsMPdyjF5y4EdTRpvm5cApsuTqRNK5jFSAgz9QYEvX5ReH4qt3XBv3eUeZc3qmqKq88at9UaLcp2ycRovjCPkqEqhik1xFroX6kRVukXuRrjEQYCxmg5JSFDF7kpDzr9P6abaQS7uKinwt6iWZ63NNmzUgRVL9UNg9K4WkdLPYKy"


#### Oracle Pool Parameters ####
# The minimum amount of Ergs required for the oracle pool to be considered funded.
minimum_pool_box_value: 44000000
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 2000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 20
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 10
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 4
# The percentage range that an oracle can deviate from the previous latest datapoint. Range: 1 to 100
outlier_range: 50


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False as no support in initial version)
stake_slashing: False
# Governance (Currently False as no support in initial version)
governance: False

