# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"

# Port which you wish the Oracle Core GET API server to run on.
# Note, the Oracle Core POST API server (to submit datapoints) will be on
# `core_api_port` + 1.
core_api_port: "9090"

# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"

# ID of the oracle pool NFT
oracle_pool_nft: "b662db51cf2dc39f110a021c2a31c74f0a1a18ffffbf73e8a051a7b8c0f09ebc"
# ID of the oracle pool participant token
oracle_pool_participant_token: "12caaacb51c89646fac9a3786eb98d0113bd57d68223ccc11754a4f67281daed"


# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "3vThpSDoLo58CtKKFLBQMmtcD5e5pJeFNNyPKnDRC4zKzhgySeTUkU71fk9mcFgHe23k1b4QuERNdcignnexcULMEenifBffiNeCdiTkgaUiGtH5D9rrsj698mRLDhANmybx8c6NunwUMoKuLsRoEYtYi8rRjuKfbNDN1HfVsgFKSyKMSnwJXa5KAuABSz5dYUgURf6M3i2bxsKKYTe4uQFEoVcbBwvfW4UxXaKqQYGB8xGLASMfHtcs9R5CBFkHyUSXh2sFy17pfdQ5emx8CgE5ZXRqx7YBYzk9jSyGqp2myT5XvBAS2uSeahNKWYKzh1XTqDc3YGLvBPHJ98bksaaSnNX4SwAhia2mXY4iCKsYf6F7p5QPNjYBXqLyzkDFxSzgQJmMg1Ybh3fx6Sg8esE9w5L7KCGEuydPkBE"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "Gxd4hMRT6J1SA6D3tfvyij49J2DCQkeZfxNVEpoZidZtS9YYsi8Jg5u3JBZQHxdmrLpVgTsnLnSbt377BRJAWFUfkdcmC1pMPFNUYBWuYaccbMxP5kV3WkGU7oxsWJauKfiGkFZPN1W1RmWVmpFbdKaCizjnMqC7TLsQ53JfBzWo5CsYj2Vn3YYbJFZiXbfVXWKjvkUHatcGxL47QnBffcKfFJun7t1tFgxowLonpFpq7SFAz4YRE6TdZarmWDjDER13pSUupfaKCZmUe3aCRhgAsdp4RHuW8n1RywcYcSjGNPVFzsGjD8GQdUrs85Xv4gobuH49S4WZFgkcoQAx3jx3GqhY9kQWwdn7Ni7v2XcKMwFFCvvzrPAKtUHLZYU4VN4RjvoFLRYJ5H"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "jL2aaqw6XU61SZznxeykLpREPzSmZv8bwbjEsJD6DMfXQLgBc12wMmPpVD81JnLxfxkT6s5nvYgbB62vkH8ChHeuVKtCPDMLTZ3gFMTa11YXXGBKvkezBENzpDBh8HsLHhnTTbMzv2sViDQpSWVNEF6G3Z9Fn2Ce6TNc5iHFZr7jGCBLtfRLKMb9RRUc9voWz9yEWpgADEkoQnDyMn5wc6xLoJsSYLfXHo2t8pyvwXfn2NotR3xFRDHU7wHXe"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "zLSQDVBaFJVVPWsvzN8begiciWsjdiFyJn9NwnLbJxMrGehDXPJnEuWm2x8gQtCutoK7crMSP9sKQBPyaPVRQXpiSr7ZoKrz4arYiJXKX1MDAfJFm9tjkY379ZiskLYHC3mmf4CQxATbY9P3mTjYw3f3Hkoxnu4yxvMCVBtRTuuRK1qh4E6aGpG8cJcpJ5qBtEsx7SrJoMZP34exMNxD1dPoaDFbuKHnoXAZmDLHnLqG3HgdPy"

#### Oracle Pool Parameters ####
# Number of oracles in pool
number_of_oracles: 4
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 2000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 5
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 5
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 4
# The percentage margin of error that an oracle can be off by. Range: 0.01 - 1.00
margin_of_error: 0.01


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False as no support in initial version)
stake_slashing: False
# Governance (Currently False as no support in initial version)
governance: False

