---
# IP Address of the node (default is local)
node-ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node-port: "9053"
# API key for the node
node-api-key: "hello"
# Your oracle address 
oracle-address: ""
# ID of the oracle pool NFT
oracle-pool-nft: ""
# ID of the oracle pool participant token
oracle-pool-participant-token: ""
# Address of the pool's "Epoch Preparation" contract
epoch-preparation-contract-address: ""
# Address of the pool's "Oracle Pool Epoch" contract
oracle-pool-epoch-contract-address: ""
# Address of the pool's "Datapoint" contract
datapoint-contract-address: ""
# Address of the "Pool Deposit" contract
pool-deposit-contract-address: ""
# Stake Slashing Config (Currently False as no support in initial version)
stake-slashing: False
# Governance (Currently False as no support in initial version)
governance: False

