# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"

# Port which you wish the API server to run on
api_port: "9090"

# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"

# ID of the oracle pool NFT
oracle_pool_nft: "b662db51cf2dc39f110a021c2a31c74f0a1a18ffffbf73e8a051a7b8c0f09ebc"
# ID of the oracle pool participant token
oracle_pool_participant_token: "12caaacb51c89646fac9a3786eb98d0113bd57d68223ccc11754a4f67281daed"


# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "6By3PvYgScgZTRMU4WghXP3Te4dgS22Es3uWT94RCZG7aastqNDYVE2WVAaVKHUhBJva8d14Xajn9JT8Jy5ZnPoRsFjD4n1Xpep7i6RwYMD4MDKTeoweaR7YeiZGF22tm5pNpKGh6Jb2Z9kH6noczi3cAdr52vp8GEy8edbEmaZtAfvh9m6X5gxEFxeo5DMndV4Pqaj3wwGm5KddCqP4wUfR8hX9BRTj7Eop5D45wGNkHguwfQvyAa43eqnwBdmnYnxVuEqvZu4cq6gJmeEvFCrg843ZtteuDF5Pzhw1vvXb4jQGgi7WfsA6SwT8t8BWyoWYHA1wXCFnAfwgvM5UCAi3184VCZtEWYq98AaqyTYCFFVCrj2z8ZGGpzcUbmKne74B46NfJa9RUFFxCUT48hTSgDrnU96wnCYRdmUUJk36EmcUEZYeQtdsj7ZG72JjiXi6wu222"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "49nTxQx5SbxHpfrxc8o7MyaTeiftKioktoH89Wk5tyzprex7sJAL9K4cznmrwS5653fQZfVme2xuDbv8drpdNvzUW4WUMyphNymTNrMH3Qr2gAtpQ4oH9yWhTjT7Z2S6HpxsGPnBDXrdZhijiKfMGw11xZ9eVMHrpwTzXU5H4e3vf8BAFxYFkvhuhpxnudk4CPK97xzhqiz8W71Rd9GU1rHgLu4zE1FXLQu7gA4hii7rCKi8AmJhTEYHuGESMyW7iqMD1uWpyQMKb14EXX3ftEuYoywSY6LxvPk95jvGCUF4jyf3SnpubkqmDmhL59nTf7RF2PFBpbEBSRm2z95J5Wrfi1SGTAXApjbyJDzXps9wfSwf9L8GtwtCdsnkcCfBNMEbVAFucCuS8YpFraJ4SYrC83NbNRx6Aw28Ly8T3B6HK5PoNEXnii1uKcTfjGjrMSZDqoYhqVpZkhSWVZRAVVoYqUNqqCKwUUeaSwCRe93BXXuKSof6BGTP9QKzV7USEn27SZFJG3Na8bWMzfqXWxX7T9EaGds4GquYUsAyKPr4ttJ3esVbSn6iK2Eh5SKZ2tVfRh7kvgrSXdxZdm1RHhB3crNCg8XpW1yHrnU8r89yUHustJjGh2XrMnUMA4Lz4UU7XzqWYGooSJSuXDtx6LD27aVtPMS37terFerX2m8bttgWM8jeFCB2guS5M54RZB7Gf44jwe17JyuXKhuNM6wJTpXBZDFTf8sVxRobLyGEPR5wJb89j7USFP8tg9idEUQVdDDJvqUQNoQavoCDAqSkRmaH312wvwLY"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "dtoETUwV6a7h8DZZEbMBtX2xbTQstvEjsvaf5TfzFMdd8bsHJNMtQgRKoiesS7q1QGrin2DTD9Gx3gDWCUPf8UZApWiWqX2neuRh5WdxD73sr477Pod7hnfuMBCPKnYFAE7JEwCRHpBrdWNfjCAAcBgvSrk6mc1NhZVfqhn5a15w8A8Mw4XvmHYoN5w2qeZkJnXNrnnsRCc2Aa2HHvweAhZhnN2cJYeVap4Xrhw9CmHY1BzGKUhpxeu6WNsHR532Wen4YqWhWjNQThZHQd2KaTWek1NBUttNi2jQANBf2feuVuzbtCsg6uE9ngf2iPNw1HWgaYw3pnRmqLatAyMktd4KhQgo9dwuNuQyMew1ZHfSeDqKXVTK5KudqT6pxxax67DxbUneQk13K2DzssRBvr4Fn5sxj79RCvcj4ngBxjdyWnPc2o1nJwWByESwmS3eD6nKwNmUXUGbP2QMq1ow28Fp4pTcwR2Jr8eUb1vkVTd351EqR3U1tbYnpNS4weDX7tVYaQ7XARby4zq1Rv6i8SxXN4yD2R2obB9JBm5w6oVfYPdmqVFqQeLTCSmF9xxH1PaEXvjaQsEJGuLrGK44ernZMJBCfdYuz5v8jpBxkWzPYVhqDRWdXpAo9UvJRoUDitZZCH2wuWZHmF2CtEEH"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "XMN8WFB9SXgi3VVU5KPtftmRSdidEZTtu6i4A4EmybbZMfju1dw1qMcUMAjVTUXxJ5U8QUb4en3Jj7Z4HaXLg5posF2vAHN2oHWF8N7jJtchxndFsQAJCeJzdAzDWfTwUSauEp65J3x1Drt1HTP7N8kJHKTGfLDT5KANj3euHB24uj24NNvQQC5cwyY2VYGhFnejSVpx1iVWHNDKtRanTDgxCetc6PKSWhJhJo8YKfpuVdrwVUDxfzMkUAeF6pHK8nj8jzVUruEEjE61WQCHootJeuQ1Y67qa2c7sunEFw2hij3raoqTFMzQ8KfDPGSQMGdAmAqMY8Xm6davayDVU172DqVgC1XLMQXF7Emr9RuVLUR8V1zhFW1QB3fv1MnmoVdAjfw1beY1ozmsyJyKsGunBFbUa5fCjuC7p68h1V4xEE3vBPY6fNrHxqFphy6TLb1YrpMVqiviz31C7Dkw1WZeFqN2DZrc8grqu4PpiqvmeJn7qLw3eKBqF762qL1gGUGrfmq4TGbMJN4Jx2pPoWSYcUE6tZV2RW1FKSje5JkKtYGSjxsXc64YZjKsg5N2KSLYr3x3HvfBpmLUB44BdLQwcwbgpByfDk2n9vzw2P4vugvL8DAc2PTTDR5ak7VqwVPvYynGEa2jUuKUddMNUduyBz7nVK5HE4ooJCECskWhE26bUe4tcXoiZBaTXCGXbm5pkyUp2hWcbGYVYifh2bKkSq7B65ph36FTwNu5GDA3EurKxqkeXfoVBDYj42QWgoDCYqgAjfryY3xsWSerFRNNztQrtvcN4y3YnNrZwT1BRXxknKaAozhRgte7uPfb287etcncgPJfMRQ1sWfRpgGNFFPwB6dy42SVPnKYw2Em5fstutjaKzYtVMMuJ7hB3gf26QEX1ekWM8ricu3pCZGwHZ7rB3dRKxd7XXXHX9Gj9gy9P9Mm4v7ypMRzi5UJ6BoqgeewESBsbuwXHitCTKrcajuyqq4TvAB5"

#### Oracle Pool Parameters ####
# Number of oracles in pool
number_of_oracles: 4
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 2000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 5
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 5
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 4
# The percentage margin of error that an oracle can be off by. Range: 0.01 - 1.00
margin_of_error: 0.01


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False as no support in initial version)
stake_slashing: False
# Governance (Currently False as no support in initial version)
governance: False

