# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"
# Your oracle address 
oracle_address: "3sSMhchmak6PHo5BXXavCiw1XkwZfsjox5N3sjVqbWVNyHojHJWBUL1JPswsEHttCiFfmVfwpFqaqjFF68D35vC9rkjCwwCFdKNR1GYdpTVbBdumH"
# ID of the oracle pool NFT
oracle_pool_nft: ""
# ID of the oracle pool participant token
oracle_pool_participant_token: ""
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: ""
# Address of the pool's "Oracle Pool Epoch" contract
live_epoch_contract_address: ""
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "3sSMhchmak6PHo5BXXavCiw1XkwZfsjox5N3sjVqbWVNyHojHJWBUL1JPswsEHttCiFfmVfwpFqaqjFF68D35vC9rkjCwwCFdKNR1GYdpTVbBdumH"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: ""
# Stake Slashing Config (Currently False as no support in initial version)
stake_slashing: False
# Governance (Currently False as no support in initial version)
governance: False

