# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"

# Port which you wish the API server to run on
api_port: "9090"

# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"

# ID of the oracle pool NFT
oracle_pool_nft: "923de7992230d2b28f011723d55616efa979af661458282516e50de0377109f3"
# ID of the oracle pool participant token
oracle_pool_participant_token: "12caaacb51c89646fac9a3786eb98d0113bd57d68223ccc11754a4f67281daed"


# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "MmsqjLTpiJ6k124bBCKpvye6A673BN5YPJPn2cEKX9g2P38TEM1aMyUVLPb8P4NhEVnxaswdFzCdvNfFsxAUuQxEjpgAz4nReFGSjfJzpMABe18FanfpB3dn6SeyR99SBNiVTsK5FYLJrxkzFBxHo5GesexJykwGtxCrooPufug4pUQrbf43Pvj6aEL2fRJrA7N56rjKoYPTH5kdoHj2UrkgStb8qr7ERU6Z2gnwPG5hiP4onh8Cknj9u7B4iuzpmizNUBJjEJtGZ5mS7Q89roLJwyNzJJRaT17WSHVjpVnXU6QgiikgFix6JA9UMYjJpo1jUkunndL58tZmPi3AxQjP3ctbuzUF3sTCARneQe7ouE68scUsVo1eTCALE7T8LcsJ36omWa1kYt9ka89pEMvkMeD76WWswT7nD6z1c3iLqM1RAtCnZscXJMnPsuLWkdmakZ8VQYJktgPyhXZdV7UXLC4yRg1mUrejnmk5vMPs49pzCUbcgVFHfAhzKop8qT9ka9iLynNMe7JPBNv2akFHPLLzeyme5oUiqayZ8XYw959AzWubbgof6UjAU4GERsV1mb1zY2YWrLVeCKM4rxaBV9kesam9rKiVbZ52uJKBo2bhFt"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "Khrk92dRT5JahB7CCi5sTFTVBR3XFkAwKvfA3MpZ62VvYux9GerjNR9aMjbzVKcet9ct1AT1Ri73zdhMS1hVFAyCTwRdKfgsiGf3XeLnZ5fka7bM3uDyCPZJ2BxYiv6txv9oV9McpF8vAWENdaN1hCEVoiJTE5QePes3UjK9hZujev5TqMpPpA5q2UbnQw5kWkJQMPekmSjxu789sdXb9VSHTaiSYzKqrNVQQHCyMcrZvecAWHCZY7MtpC8nX775MShxBXai5jcbkUgi9xNjvaaZmMvEY22X7bSnEa8rWB4mhiYVjH52AKgMdADBhFtkxoW78nuzD1X1xskifJQ6LhXdr2Hdg7QhNKULkTXU3EG2yrsfSPWSazkL2xKVVAdBDnhEMEeVjeaq4kWYjcQjyzQGHNeEZ6yQdB5DJXnbED3wtATnD1oM2ku2FAiy2tLy5UDB3S1MR776ibZSGJetx13Hift2TStwpw94Ykj6Vq6vBAVfKrvAnzPVV3TxKYko9NFGYMY3fhn7Q8sfHKG4Z4c79t2U8dX28X4rYWBQ2AUTSySWGjgWMx6ou1ybkwkYAhesDGNr1XMr1szDiZTGFGEhSZSM9iTpME5ptCMMzvE2LAjGVmzT3EKuNNBFVACucvR9CbV5YCiT3fqNWdcmAZCYupmK4gfSDiL4ax3CaFNHXW3JA2xJkwFpDiEGbxHBchC1XwDDFqRnteihrgeJDae6RHjvG6VFjAudb3TUZDF9QraNDhBG2GEs232FowbnXc5FDSB5zpMcrEV3G8Yey5ScQGEmG8Qw3W3xyJFKDnRaUjjx33RPSBGGYbddijmaFbT1Rg4bZNPctr5x3MAqLDs8c9gZFopNkFQE7utaRL6d1Fz2pRpUwT5e8LNPLZmo4vftF1GfirjNwfHCRe9EH11vWmvT3Rf3qiuG6c1BkxuZmqiJT3ZRUN5wG4aoXHD5esxqUMYa61eERGSp7"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "3YhP6PnJY49GuBwJFjDEcVt2Pv4xGfdxxABfVaDTZyHJZrD2bdS83ecsjG4m4BNE8HpjDZV5sc23kaTEjKd4K3grhm4UMTcqVKiRWFEn4USryCWnqNoZfJ78rPLGtc3CHnDsCq86LYK6Z3DT5nqoNQqtcgripSrz76Q5YjPSwJFrcWcp3AnjfUVeBw9XgFMj3s4QNqCuGZGAcVevBfmAGvE65GDnuhdkggtrwDGoeuv2bHi6zXaALeMLyhQFdn79dmrPMA6h11UdDf9sUw1wmfXHXTWXjzjyPjYJUf6W3GKEqQBzKfLq3TFwa9b7fYh5PJDN8aLk5kMuS1AM6t44gdiHMfFb1GhYFGUTZQLgKJywXN5UqTkCQVAtYNX1e3Di8jGTwZjNaSCfRvnoAC7qPzJaeNkjxCMqBcycSKxqFWd67cKersPm3D8LeqVPUDDbKFXrMDB2JMDkJLx9beixboNtZzKURSHuqmQ9AN6XiJBYLBypE7oGYRtvBBHvnjL8EhJSWM2rrCYreB6yuJnYsQ8htvJ494yKK2Jvm9izyxJE97kggTwEYW9xwaTbzbCS3GnmhDYE9rQ7SJEfp4UwN8dYkDiW9eVDLBjmxW26cjamkA2vZxCiBUtBaPGyuvVQzxPsRSXxGtkm8WfGiFw3i5c9GxhUxiLYT7We9CsX9bKJFiAKApM6sdeJQPWKZyxAPv7NBgKX6XfGMgV5jQzuu4wXTT5z6QkWYwA3bg4r5uaA5MgoqKYmTCoC62Y46REeMXbHMfAkNxRgwXMb8aESnqaEwYBMuimeHVsxqtfjbcKjhuG9jx4pCFMjBmqNcJ"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "4793vgviYhQLYeuKrHfL8158F4G2CUAmmxYUk6h63Ukis3zeT5LMYViaDke384bFo9GfNuiWmMSq8ohmAoeFaBhLwsnzHJYc3LXGDA9Gorijdzy6hXm25ZwV4FFQ1oZrb9v6ToRN6kVzxVuqM5JFuGPd6T9xqSEvJuz8kx8ZnHaxYzMaDcE8MUBnMKxkvaKqvurGA9YbV1GuNSJVyp7tBN53HoyzLowLkmyfcvvVyEY7WgcvbPWmtepC9KQqisiMnWhNTAtP4voV9QfL89xhj6eYiz8JmknyJS7YELqpdDpK1Z8xKhySVpAGTaunzSmxaPd3bARPzxXkipgiWMUULwyVDrYscMkS3xfwBhq52Js7h4WRGbTAYx3EmTXGkGwc8zt6yoLy2pnFCBz5pKyhEQU5guuwE55i1ePERCrweZFE5AbmQamkCyqGUqoyNZUjjgDy8vFgVSMVbpCZvbWymncALmwypQLUX8nbnb5Qryrpb4Ru8bNTrN9og22TGJEX3QSHnoFpoKBZzexL1CCQzkutanhXdSZSgrxHKJY8z4nmvCL86Gqp19sovTFQyeniHTUAdJqguwJ6cbW7wH9vTCZAnCb1J3XHBLpfj4A3pZbm5kUCZFuuq2ouDKkqA24Z5hQFeLupxRdJ8R8egKMFcqP6gMaxHuMpU33d6uYNVbRLvJ6nmTVpwfevrq6xLwm4SArLTjkwQQszcmt2FZ5ZREKW8LJuAHSob2eAgAczZxW3J5oFVswC2oxLmdN8NR4vHCipTytgiuAVQDizaQm78hmGxxhDTG1R9f6bPuHPNnMFud7xHY1vFGThJb1TeqUsxKsrLd2vPaF1CVpV5zHS4EoSjBTtD5GPV44YKUYYZ8rtN158QNFpDDUNsm93caE8Wv6DPyqo6D2rmNhfUU3YZYwBTEG2hGqWtwzHZLtmqduv9NGFp6ffBWFwkmE4HoSSKMo2PqE8U2RwWncBbg5deroWKxWSWWGcNbCtmwceNdWX4WtyA7us81Yx6gia7jZZo2F2ThaTrAPL64XQYW5uS6opQ3tkZaHYqiWXhnVVK5bzaW2vuzrrukaMA3cxy4hjvWJM73e7wiZA8ciD4NgNWZgoe8asYPkrbWSt7SbQua7VDgAz2y7WCQJCc8bw9yNh7pgkivFcMM27ys9FGL"

#### Oracle Pool Parameters ####
# Number of oracles in pool
number_of_oracles: 4
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 2000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 4
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 4
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 2
# The percentage margin of error that an oracle can be off by. Range: 0.01 - 1.00
margin_of_error: 0.01


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False as no support in initial version)
stake_slashing: False
# Governance (Currently False as no support in initial version)
governance: False

