#### Node Parameters ####
# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"


#### Core API Parameters ####
# Port which you wish the Oracle Core GET API server to run on.
# Note, the Oracle Core POST API server (to submit datapoints) will be on
# `core_api_port` + 1.
core_api_port: "9070"


#### Local Oracle Parameters ####
# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"
# The base fee constant that all action txs use to calculate fee.
# Adjust if blockchain is congested/higher tx fees are required.
base_fee: 1100000


#### Pool Token Ids ####
# ID of the oracle pool participant token
oracle_pool_participant_token: "f0ff151ed1250fb305a74bf843f8de1be6a13e3d1a37229b94391e648357a4ca"
# ID of the oracle pool NFT
oracle_pool_nft: "323b13f731b00bbf33899f00543f851b20d794c21e9b81ba5f71cec8289c0619"

#### Pool Smart Contract Addresses ####
# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "8D6pdYVRvF6RA3pntG56smWBZJ7MHAbHdMsk4BmCvL6JoneTC4aLFHRqyUGvSLgmcAv4VBET9Y31a4Ajpfw4Ek7DG5waDNktq5Ft1i57YoYPC91T7fVr2ZTkX7yfonFxuadnmWwMFQcLV1bpPTD9r7JFsKtKSXWTBozn4A5T7YHVys1PR25mgMdEsu5f1DDz6TM4XAM7LovcrRT5q9emcM5UPHQZc2JY7pYjH72mWrGMYcmkMwubUnJC5F3EeAurq9Z7LUmsizmGAuWqomtkjxSSQLpSoS5kWry3rtNAbvj8XR4DWKKbh4Qfepng1bqsCNRvhAf1JLWfekKciY9YuLKesf9kdP46oJEk7pzVni18ucRK1ETE2dCrQZekrk97sqZxGR4GD6wuGqBhMugyqQ5gApUEf3xxpdtj836zLA6VRVHL4Jc3ftmyXmwuC5d3wEdJqyxrATcdH8fbDu86kqvXCcm4WGgd3EbqQSDAgsXwdz617TvK6rwz2W9eXuBf6euwtNNLccSwUHj45EC9okiShob3R6oexhgB568Gprcw4rLRYNEgSULKEbazn"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "Gxd4hMRT6H2cFm9DGywqDwCMYkpo2Zmz966CSB9WrbNcUXTdUw4d5RTpJTL3nn36Y7X7gcM1Lq8DCvf3ZkE6DXohUKikt2TTGbw8gQcBaKgaogzMfxEhHQVYkuHHNwJTQPeWqEz64tgGnwmkr2U6CKz5QWfCpErLBHgrBsH2Xy2dheJxp4cvXpU3tfDQse5otig9465bCQsZrMU85Ltjdpi2duCGrgyRvV1Aoe4wPdzCV7R3CEtmnoDFSw6g6tbkieLz9brrB81nFM3KCUeQTvKPn9kuUj6PKnuNsDeTfXe1u78khQcoEYZNVWoeX9KpiqNDmdWcYGhniHDSC3bVdDizsQxHC9hQ2YV4nUQjx1SsNjH96Dbcnz4hg3pDS9Z4EBWcX5Eb7yFoV7"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "jL2aaqw6XU61SZznwBKSYk5uhvGSniF7Wy4yzxFC26osVdyEHiDqzzpgpkVYg2GeCazyrreUj3R22S5SZSvXkcb1ATwcMzP9kCoCjmdqLYWuX5KankE8dFnv2D9aDyv7GuzEsgEmQbz9tDi4vyGom5FHdjUf4ZgJDm6WnP9sDhNpyV7mtBGaszNKHn211cKR68QmRsc73juzEo7UJEmK9TKkreevViv2L6M4qy25nWU4BYgkj8jjZ8HNjEPjR"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "zLSQDVBaFFXNwLXqJmgrB9qkdfm66j3dHhH42d88WjkMYdmaJA2dMxQ38D51nVaPqKnNBnihXdY8mY98ktKMei7pgRDZEpT9Y6QJCr43TtiUexQcNjFq2BGHwqDQ5WLm3xvMQw2A2ZzCkkph4WN9gY5BHzyikXZYFPypaPKDnh2cs5F2Nith3cn7XzDRn1orcbbre3grtobazsFuShHYtkYQmf1pJAzvvMm28Kd9SfMKYAe7fZ"


#### Oracle Pool Parameters ####
# The minimum amount of Ergs required for the oracle pool to be considered funded.
minimum_pool_box_value: 22200000
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 2000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 20
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 10
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 4
# The percentage range that the minimum datapoint can deviate from the maximum datapoint submit by oracles in the current epoch. Range: 1 to 100
deviation_range: 5
# Number of oracle who must be within deviation range of each other in order to reach consensus and finalize a new datapoint.
consensus_num: 3


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False, slated for future support)
stake_slashing: False
# Governance (Currently False, slated for future support)
governance: False

