[package]
name = "oracle-core"
version = "0.1.0"
authors = ["Robert Kornacki <11645932+robkorn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
json = "0.12.4"
reqwest = { version = "0.10.8", features = ["blocking"] }
serde_json = "1.0.57"
sincere = "0.6.6"
thiserror = "1.0.20"
anyhow = "1.0.32"
base16 = "0.2.1"
blake2b_simd = "0.5.10"
openssl = { version = "0.10", features = ["vendored"] }
log = "0.4.11"
simple-logging = "2.0.2"
log-panics = "2.0.0"
crossbeam = "0.7.3"
# ergo-lib = { version = "^0.15.0", features = ["rest"] }
# ergo-lib = { version = "^0.15.0", path = "../../sigma-rust/ergo-lib", features = ["rest"] }
ergo-lib = { git = "https://github.com/ergoplatform/sigma-rust", rev = "35bfd30c9cb9223af5510925942ba301e638931e" }
ergo-node-interface = { git = "https://github.com/ergoplatform/ergo-node-interface-rust", rev = "ca123f5e2894d2f397155b97024ca4af8fd0c1d9" }
derive_more = "0.99"
bounded-vec = { version = "^0.5.0" }

[dev-dependencies]
# sigma-test-util = { version = "^0.3.0", path = "../../sigma-rust/sigma-test-util" }
ergo-lib = { git = "https://github.com/ergoplatform/sigma-rust", rev = "35bfd30c9cb9223af5510925942ba301e638931e" , features = ["arbitrary"]}
proptest = {version = "1.0.0"}
proptest-derive = {version = "0.3.0"}
sigma-test-util = {version = "^0.3.0"}
