#### Node Parameters ####
# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"

#### Core API Parameters ####
# Port which you wish the Oracle Core GET API server to run on.
# Note, the Oracle Core POST API server (to submit datapoints) will be on
# `core_api_port` + 1.
core_api_port: "9090"

#### Local Oracle Parameters ####
# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"
# The base fee constant that all action txs use to calculate fee.
# Adjust if blockchain is congested/higher tx fees are required.
base_fee: 1100000

#### Pool Token Ids ####
# ID of the oracle pool participant token
oracle_pool_participant_token: "78180c57b903b2d144f60b61ab5256e97f1bfcd7fec65c1c86dc83854230a5d9"
# ID of the oracle pool NFT
oracle_pool_nft: "54acaa0c6d5d3bc66b88364a423b5f156ed763f7236d437adb44d70787bc0f95"

#### Pool Smart Contract Addresses ####
# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: 8D6pdYVRvF6PeiuSWVBR4x2RqKKCjPPqMyTpmRho6EpfWMqnwN4uedKYYTkniyKPEjnjHXpLFLE8a7uszfA7VmsJSHiQJoUcvi8zEWMtfWsd4gpmZmAvttujn4Z4v6xBK3XkNv8DrCQAR3KGubrBFsWPS5G9KP6hCqWn7pt9giPrAfD4ZyNv7nQzesBcL3mu6tjQiHeMR84d9DVHUGEiKEeMmYC6wgTyPSGKfYJM3B5bjVhGqmUYTD6A4B6iubUng1jLVQ9EKgWPnFCH25PS85aCgfkZwyJjVhHTkjthJhNxB3RKvmihFbCnwhooXReqXZ4P5Y258VmvgiQHo58hamdTacYD45hPB4A7F9NivUm2hBwt6sXnxqZwU5NAh4wBUrgSRuLZeuPfQ6soRs3gaWPT6WgxowTt35D7ccHihqX4YmumJ1wNGbHEbTkAUKuc5bTawcT1kaKY6b44fLBRPVavDxkiEhrjVhFHQa2ZE9SxqUh4joRNQG9Ja7NQZn3DiNuADFMPp2FGSc4WPUZHs1EjqHVUhzgZnS6WWxPubEjjGJnftYejcu3415yB8"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: 2Qgfhy6m7AhxRU3xMHBXLtbXLWj6cs8cvSCsJdHh9rkZx64ZnzDDxBWBh5GsPkSuXcxfMGt36fLchZk2fMxXqxBzUcisq7HRo8kZA3Gp9fjqJYZAtuomUSkirWTEiM6X8kgahypcsRAvEt2PcXX2BLcJo1VfR7XggvhnNLCTqBxRDaWMVsERXVWVuoEU3DPNz67EVVnRdEqpuMUo7yoGZCSDufujyWHWszNmdCMEDBuF9WDEw3efnFMg8W81AYZJZcnAggfoZNtpjYx7stN26GRvW32m9x8AnW2Sz8gigg3rTyhavPFgwA2D1W59UQ1pTP2Dgb5kDT1yRi42Q5uimXaAbzGLqhz2tMmh1ds5X7N9LbKNnoyqe9N9agJ7GVeFBt6VUYAmfwuguWrgeA62kk2qerckhNdyBPjwSQmKMzomnwxkNZ5sKwgAAnjzMwfyJwbyueACgFe4dWomTSEXEDFBG4gqCTW2NhGw1p"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: jL2aaqw6XU61SZznwZeLEryve79s26LKMtJDCG5AMu3jQ8oUxQ8wREoWLPepqTWSkC4WfFvoQPKmB92arFHyGL58Nz5ADsx557kdWELBvtLorXibLGsMxrAQAxVQgiFMuyhpwyN3XA3kYuaB3k8BM3wdFd8c3GPp1YR24ve3jMEChrTeKodZ8RpKQSM7aaR9kTdeBfqaxjoNBpN3q7o5wYUCX4WppQp5saMgyZmsL9crNnR4CbVmywQtp8145"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "zLSQDVBaL7d8mjWMSTdbA5DReg1kqMxp5FW8patzNCziV2p2z4xzi3uSeX9Y8mcPhfC7i6its7uR4mNxU1ogLXwipePGBj9FTmZkhoXQ5qe9dVGsqDk3wMpdGq6xseNJi1Hq8ntbuXdXxfeBmE7jTFXaAL3mMMmR2nUksU167XjGYHp9ho5WkpnjRcP1Zn34goNFkvNiXa4NU2irPpLk1kYdQdm6neJvdtNYFRvCLvoPhdpVVV"

#### Oracle Pool Parameters ####
# The minimum amount of Ergs required for the oracle pool to be considered funded.
minimum_pool_box_value: 222000000
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 20000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 10
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 5
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 3
# The percentage range that the minimum datapoint can deviate from the maximum datapoint submit by oracles in the current epoch. Range: 1 to 100
deviation_range: 5
# Number of oracle who must be within deviation range of each other in order to reach consensus and finalize a new datapoint.
consensus_num: 4

#### Oracle Pool Features ####
# Stake Slashing Config (Currently False, slated for future support)
stake_slashing: False
# Governance (Currently False, slated for future support)
governance: False
