#### Node Parameters ####
# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"


#### Core API Parameters ####
# Port which you wish the Oracle Core GET API server to run on.
# Note, the Oracle Core POST API server (to submit datapoints) will be on
# `core_api_port` + 1.
core_api_port: "9090"


#### Local Oracle Parameters ####
# Your oracle address
oracle_address: "9fj9NJpzo13HfNyCdzyfNP8zAfjiTY3pys1JP5wCzez8MiP8QbF"
# The base fee constant that all action txs use to calculate fee.
# Adjust if blockchain is congested/higher tx fees are required.
base_fee: 1100000


#### Pool Token Ids ####
# ID of the oracle pool participant token
oracle_pool_participant_token: "749fe0b8c63213be3451af2578eacabd620a9e687f5c55c54f1ec571b17c9c85"
# ID of the oracle pool NFT
oracle_pool_nft: "0fb1eca4646950743bc5a8c341c16871a0ad9b4077e3b276bf93855d51a042d1"

#### Pool Smart Contract Addresses ####
# Address of the pool's "Live Epoch" contract
live_epoch_contract_address: "8D6pdYVRvF6PcDZZ8HXaEv1VyWmYC8VV5mfmuVPCBHLCzzjWUu6vvrpJvN8uT7rJMKzJbGmVcaDJirPFeuTV1jgk3E1sF8KYKaQjvohyXfPsZhCqhsQ8oh5c3EKbmC4DeMBBxaEzUZZFmvFwpsoGMJvhwQKpwuEQZruTwdzjUxwfFMKyNtTBbAr3Pmz6NeB5ewyj2bSFcfN791G2jKB3VENA7pncaX3bPhL6aEDJstFBELa9a7uTeevA1sjcUwTyUDfShwyM2hE1RxRrCFMfiuzcR3nJYVLEsn3Y1ge6ThjQg8H3xFpXsJ6SfXtFhX2PdnhyjMD9mtkCjM6icsqNp12R7J58HenC1fv8KpuBU7GEmQAHEFr28Gr8GKafhiTsXzjtqbiV9b78A4wtWUBgbEPfrKhV1eB3fVKPQ73Gw8xwxTLBbXLKyVHT9kcrnUPQBGij4H1oaeNz2cr7eMdwiP2aA4XjUHDnct7ZiHn243UnqP7gveBGf1fcZMYNkjiXhFCRsjMhBQtjE9gtBMNoTJd3Y9tdjYn1YcHWbKQLvj27eD4XXpSSEXodBFuhM"
# Address of the pool's "Epoch Preparation" contract
epoch_preparation_contract_address: "2DSWBK78v9sqbTLKupuf7tmXwVdNr6jPZPjxvaNxgCRkYMPvWagyAu8qo3Uq8Df1AdWK12B88MFEnd71bFiAA1y9hycNziw99PgyaaLiWhdHUDfTziUoZTLbQWTEnaAeqcwzodotewJxQpGEW4Hx5DBkqQgrYvSvXGqHdhZHLztee3Sa8SMKEsRuTEhrR6jCYvQbwYfLG7sPfXoBGWfARLwmjSm2UkzJTYXwNEvqmr89KAVn3U3UFsxbabLoe56oddeRfpNSMJvuzf8UzjiYt7ir2uBPAJMm8qRxtxAu2Ka6XdFTUtbyE7NEeLtXFvkv2RoorZfzMNkDixt5PHNM8WZiq2j1kcsAtcR5ctzB8bw62ATkR6JVa97D6GHTM7XZTgY5X4dnEuTg4PWm"
# Address of the pool's "Datapoint" contract
datapoint_contract_address: "jL2aaqw6XU61SZznvnw681zGfmUQkZouLZ8uvwy36MJRbqZRxr7sFbLJKMDEFy41GXWBChWqa6tRDst9xPdPsq1T1UTgYqLBCexE99Vgc68b3TjV6ai5yNtv1dXwJrz5iAqCKcagzTf8ZSA2Nt2hAMLCNFyRxLaDbYc3Wj4CuL1hvgYEPwnCJfRURkNReWa8zrPBY212EynDKGa3RdxWesA4AwaKtYwaaNjwdCaQ5bvScjw45mgKEJDmq8F1x"
# Address of the "Pool Deposit" contract
pool_deposit_contract_address: "zLSQDVBaHb3fokB31Fv5jdpRdGAbnkNgsFas3BrADM1XBFqfZjGNAh7K94gRRdyjcRtq6B9tGKRkThczZR5vtYzAD5TTdML2bpBmpdZqkGVb6kSj1wH8JEiqx1L54GcU9CtFRdN64B1sccA41DR3t1uYJh3BBCDcBiZyVFqMF3MenohN5gt8JTMcUzwzDjCUbtmt2MULpUDZvNPgnwFmFQTAqEHKEkunaKZPHs8WsnMJzhXHbU"


#### Oracle Pool Parameters ####
# The minimum amount of Ergs required for the oracle pool to be considered funded.
minimum_pool_box_value: 222000000
# The payout in Ergs that a single oracle earns on successful datapoint posting
oracle_payout_price: 20000000
# Length of the oracle pool's live epoch in blocks
live_epoch_length: 20
# Length of the oracle pool's epoch preparation stage in blocks
epoch_preparation_length: 10
# Buffer length in blocks that is the upper limit for an oracle pool to create a new epoch
buffer_length: 4
# The percentage range that the minimum datapoint can deviate from the maximum datapoint submit by oracles in the current epoch. Range: 1 to 100
deviation_range: 5
# Number of oracle who must be within deviation range of each other in order to reach consensus and finalize a new datapoint.
consensus_num: 3


#### Oracle Pool Features ####
# Stake Slashing Config (Currently False, slated for future support)
stake_slashing: False
# Governance (Currently False, slated for future support)
governance: False

