#### Node Parameters ####
# IP Address of the node (default is local)
node_ip: "0.0.0.0"
# Port that the node is on (default is 9053)
node_port: "9053"
# API key for the node
node_api_key: "hello"

#### Core API Parameters ####
# Port which you wish the Oracle Core GET API server to run on.
core_api_port: "9010"

#### Local Oracle Parameters ####
# Your oracle address
oracle_address: "9iHyKxXs2ZNLMp9N9gbUT9V8gTbsV7HED1C1VhttMfBUMPDyF7r"
# The base fee constant that all action txs use to calculate fee.
# Adjust if blockchain is congested/higher tx fees are required.
base_fee: 1100000

#### Pool Token Ids ####
# ID of the oracle pool participant token
oracle_pool_participant_token: "5579de48d16e54ddb34df789d418e1f10c119e15a824ea32dc21696c067f9fbe"
# ID of the oracle pool NFT
oracle_pool_nft: "008a94c8c76bbaa1f0a346697d1794eb31d94b37e5533af9cc0b6932bf159339"

#### Oracle Pool Parameters ####
# The number of blocks for which a rate is locked in the pool box.
# Each block is 2 mins on average
# For a fast changing rate, use shorter value (such as 5)
epoch_length: 4
# The max error allowed in the declared start height of new a epoch
# Ideally, this should be the height at which tx gets mined
# However, due to congestion, we allow this error margin
buffer_length: 2
# Maximum allowed difference between the first and last data points
# in terms of the first data point
# Data points are sorted in increasing order
max_deviation_percent: 5
# The minimum number of fresh data points needed to refresh pool box
# A data point is fresh if it has been posted in the last epochLength blocks
min_data_points: 3